=== larry4xie/websecurity/src/main/resources/resources/websecurity-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by xang (xang) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="websecurity">
		<xs:annotation>
			<xs:documentation>websecurity XML 配置根元素</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="beanfactory" minOccurs="0"/>
				<xs:element ref="global-userdetails-helper" minOccurs="0"/>
				<xs:element ref="global-exclude-url-patterns" minOccurs="0"/>
				<xs:element ref="global-special-pages">
					<xs:annotation>
						<xs:documentation>全局的特别的页面，所有domain都会继承</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="domains"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="beanfactory">
		<xs:annotation>
			<xs:documentation>bean加载器</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="collapse"/>
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="global-userdetails-helper">
		<xs:annotation>
			<xs:documentation>认证信息加载器</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="collapse"/>
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="global-exclude-url-patterns">
		<xs:annotation>
			<xs:documentation>全局的不拦截的路径模式</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="url" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="global-special-pages">
		<xs:annotation>
			<xs:documentation>特别的页面，给拦截器使用</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="page" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="url">
		<xs:annotation>
			<xs:documentation>路径[模式]</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="collapse"/>
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="page">
		<xs:annotation>
			<xs:documentation>页面</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:whiteSpace value="collapse"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:whiteSpace value="collapse"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="domains">
		<xs:annotation>
			<xs:documentation>websecurity管理的域列表</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="domain" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="domain">
		<xs:annotation>
			<xs:documentation>websecurity管理的域</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="filter-url-patterns"/>
				<xs:element ref="exclude-url-patterns" minOccurs="0"/>
				<xs:element ref="special-pages" minOccurs="0"/>
				<xs:element ref="userdetails-helper" minOccurs="0"/>
				<xs:element ref="interceptors"/>
			</xs:all>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:whiteSpace value="collapse"/>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="session" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:whiteSpace value="collapse"/>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="short-circuit">
				<xs:annotation>
					<xs:documentation>true|false</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:whiteSpace value="collapse"/>
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="filter-url-patterns">
		<xs:annotation>
			<xs:documentation>域拦截的路径模式</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="url" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="exclude-url-patterns">
		<xs:annotation>
			<xs:documentation>域不拦截的路径模式</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="url" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="special-pages">
		<xs:annotation>
			<xs:documentation>特别的页面，给拦截器使用</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="page" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="userdetails-helper">
		<xs:annotation>
			<xs:documentation>认证信息加载器</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="collapse"/>
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="interceptors">
		<xs:annotation>
			<xs:documentation>域的拦截器列表</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="interceptor" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="interceptor">
		<xs:annotation>
			<xs:documentation>拦截器</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="bean" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:whiteSpace value="collapse"/>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="order" type="xs:int"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== larry4xie/websecurity/src/main/resources/resources/websecurity.xml
<?xml version="1.0" encoding="UTF-8"?>
<websecurity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="websecurity-1.0.xsd">
	<beanfactory>cn.com.cybertech.websecurity.beanfactory.SpringBeanFactory</beanfactory><!-- 不是必填项 -->
	
	<global-userdetails-helper>cn.com.cybertech.websecurity.support.metadata.impl.SessionUserDetailsHelper</global-userdetails-helper><!-- 不是必填项 -->
	<global-exclude-url-patterns><!-- 不是必填项 -->
		<url>/common/**</url>
	</global-exclude-url-patterns>
	<global-special-pages> <!-- 不是必填项 -->
		<page name="access-denied-page" value="/accessDenied.jsp" /> <!-- 不是必填项 -->
		<page name="invalid-session-url" value="/sessionTimeout.jsp" /> <!-- 不是必填项 -->
	</global-special-pages>
	
	<domains> <!-- 必填项 -->
		<domain name="user" session="user[, other]" short-circuit="true"> <!-- 必填项 -->
			<filter-url-patterns> <!-- 必填项 -->
				<url>/user/**</url>
			</filter-url-patterns>
			
			<exclude-url-patterns> <!-- 不是必填项 -->
				<url>/user/common/**</url>
			</exclude-url-patterns>
			
			<special-pages> <!-- 不是必填项 -->
				<page name="access-denied-page" value="/useraccessDenied.jsp" /> <!-- 不是必填项 -->
				<page name="invalid-session-url" value="/usersessionTimeout.jsp" /> <!-- 不是必填项 -->
				<!-- 其他page,每一个拦截器都可以获取配置的值 -->
			</special-pages>
			
			<userdetails-helper>cn.com.cybertech.websecurity.support.metadata.impl.SessionUserDetailsHelper</userdetails-helper><!-- 不是必填项 -->
			
			<interceptors> <!-- 必填项 -->
				<interceptor bean="filterAuthenticationInterceptor" /> <!-- 不是必填项-->
				<!--  
				<interceptor bean="" order="" />
				-->
			</interceptors>
		</domain>
		
		<domain name="admin" session="admin">
			<filter-url-patterns>
				<url>/admin/**</url>
			</filter-url-patterns>
			
			<special-pages>
				<page name="access-denied-page" value="/adminaccessDenied.jsp" />
				<page name="invalid-session-url" value="/adminsessionTimeout.jsp" />
			</special-pages>
			
			<interceptors>
				<interceptor bean="filterAuthenticationInterceptor" />
			</interceptors>
		</domain>
	</domains>
</websecurity>
